const storeCOnfig = {
  state: {
    settings: {
      centerMode: true,
      centerPadding: "5px",
      focusOnSelect: true,
      infinite: true,
      slidesToShow: 6,
      slidesToScroll: 1,
      speed: 500,
      swipeToSlide: true,
      autoplaySpeed: 4000,
    },
    settings_promotion: {
      centerMode: true,
      centerPadding: "20px",
      focusOnSelect: true,
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 1,
      speed: 500,
      swipeToSlide: true,
      autoplaySpeed: 4000,
    },
    seatLists:
    [
      {isSold: false, rowSeat: 'A', numberSeat: '1'},
      {isSold: false, rowSeat: 'A', numberSeat: '2'},
      {isSold: false, rowSeat: 'A', numberSeat: '3'},
      {isSold: false, rowSeat: 'A', numberSeat: '4'},
      {isSold: false, rowSeat: 'A', numberSeat: '5'},
      {isSold: false, rowSeat: 'A', numberSeat: '6'},
      {isSold: false, rowSeat: 'A', numberSeat: '7'},
      {isSold: false, rowSeat: 'A', numberSeat: '8'},
      {isSold: false, rowSeat: 'A', numberSeat: '9'},
      {isSold: false, rowSeat: 'A', numberSeat: '10'},
      {isSold: false, rowSeat: 'B', numberSeat: '1'},
      {isSold: false, rowSeat: 'B', numberSeat: '2'},
      {isSold: false, rowSeat: 'B', numberSeat: '3'},
      {isSold: false, rowSeat: 'B', numberSeat: '4'},
      {isSold: false, rowSeat: 'B', numberSeat: '5'},
      {isSold: false, rowSeat: 'B', numberSeat: '6'},
      {isSold: false, rowSeat: 'B', numberSeat: '7'},
      {isSold: false, rowSeat: 'B', numberSeat: '8'},
      {isSold: false, rowSeat: 'B', numberSeat: '9'},
      {isSold: false, rowSeat: 'B', numberSeat: '10'},
      {isSold: false, rowSeat: 'C', numberSeat: '1'},
      {isSold: false, rowSeat: 'C', numberSeat: '2'},
      {isSold: false, rowSeat: 'C', numberSeat: '3'},
      {isSold: false, rowSeat: 'C', numberSeat: '4'},
      {isSold: false, rowSeat: 'C', numberSeat: '5'},
      {isSold: false, rowSeat: 'C', numberSeat: '6'},
      {isSold: false, rowSeat: 'C', numberSeat: '7'},
      {isSold: false, rowSeat: 'C', numberSeat: '8'},
      {isSold: false, rowSeat: 'C', numberSeat: '9'},
      {isSold: false, rowSeat: 'C', numberSeat: '10'},
      {isSold: false, rowSeat: 'D', numberSeat: '1'},
      {isSold: false, rowSeat: 'D', numberSeat: '2'},
      {isSold: false, rowSeat: 'D', numberSeat: '3'},
      {isSold: false, rowSeat: 'D', numberSeat: '4'},
      {isSold: false, rowSeat: 'D', numberSeat: '5'},
      {isSold: false, rowSeat: 'D', numberSeat: '6'},
      {isSold: false, rowSeat: 'D', numberSeat: '7'},
      {isSold: false, rowSeat: 'D', numberSeat: '8'},
      {isSold: false, rowSeat: 'D', numberSeat: '9'},
      {isSold: false, rowSeat: 'D', numberSeat: '10'},
      {isSold: false, rowSeat: 'E', numberSeat: '1'},
      {isSold: false, rowSeat: 'E', numberSeat: '2'},
      {isSold: false, rowSeat: 'E', numberSeat: '3'},
      {isSold: false, rowSeat: 'E', numberSeat: '4'},
      {isSold: false, rowSeat: 'E', numberSeat: '5'},
      {isSold: false, rowSeat: 'E', numberSeat: '6'},
      {isSold: false, rowSeat: 'E', numberSeat: '7'},
      {isSold: false, rowSeat: 'E', numberSeat: '8'},
      {isSold: false, rowSeat: 'E', numberSeat: '9'},
      {isSold: false, rowSeat: 'E', numberSeat: '10'},
      {isSold: false, rowSeat: 'F', numberSeat: '1'},
      {isSold: false, rowSeat: 'F', numberSeat: '2'},
      {isSold: false, rowSeat: 'F', numberSeat: '3'},
      {isSold: false, rowSeat: 'F', numberSeat: '4'},
      {isSold: false, rowSeat: 'F', numberSeat: '5'},
      {isSold: false, rowSeat: 'F', numberSeat: '6'},
      {isSold: false, rowSeat: 'F', numberSeat: '7'},
      {isSold: false, rowSeat: 'F', numberSeat: '8'},
      {isSold: false, rowSeat: 'F', numberSeat: '9'},
      {isSold: false, rowSeat: 'F', numberSeat: '10'},
      {isSold: false, rowSeat: 'G', numberSeat: '1'},
      {isSold: false, rowSeat: 'G', numberSeat: '2'},
      {isSold: false, rowSeat: 'G', numberSeat: '3'},
      {isSold: false, rowSeat: 'G', numberSeat: '4'},
      {isSold: false, rowSeat: 'G', numberSeat: '5'},
      {isSold: false, rowSeat: 'G', numberSeat: '6'},
      {isSold: false, rowSeat: 'G', numberSeat: '7'},
      {isSold: false, rowSeat: 'G', numberSeat: '8'},
      {isSold: false, rowSeat: 'G', numberSeat: '9'},
      {isSold: false, rowSeat: 'G', numberSeat: '10'},
      {isSold: false, rowSeat: 'H', numberSeat: '1'},
      {isSold: false, rowSeat: 'H', numberSeat: '2'},
      {isSold: false, rowSeat: 'H', numberSeat: '3'},
      {isSold: false, rowSeat: 'H', numberSeat: '4'},
      {isSold: false, rowSeat: 'H', numberSeat: '5'},
      {isSold: false, rowSeat: 'H', numberSeat: '6'},
      {isSold: false, rowSeat: 'H', numberSeat: '7'},
      {isSold: false, rowSeat: 'H', numberSeat: '8'},
      {isSold: false, rowSeat: 'H', numberSeat: '9'},
      {isSold: false, rowSeat: 'H', numberSeat: '10'},
    ]
  }
}

export default storeCOnfig;