const storeCOnfig = {
  state: {
    settings: {
      centerMode: true,
      centerPadding: "5px",
      focusOnSelect: true,
      infinite: true,
      slidesToShow: 6,
      slidesToScroll: 1,
      speed: 500,
      swipeToSlide: true,
      autoplaySpeed: 4000,
    },
    settings_promotion: {
      centerMode: true,
      centerPadding: "20px",
      focusOnSelect: true,
      infinite: true,
      slidesToShow: 3,
      slidesToScroll: 1,
      speed: 500,
      swipeToSlide: true,
      autoplaySpeed: 4000,
    },
    seatLists:
    [
      {id:'1', rowSeat: 'A', numberSeat: '1', selected: false},
      {id:'2', rowSeat: 'A', numberSeat: '2', selected: false},
      {id:'3', rowSeat: 'A',numberSeat: '3', selected: false},
      {id:'4', rowSeat: 'A',numberSeat: '4', selected: false},
      {id:'5', rowSeat: 'A',numberSeat: '5', selected: false},
      {id:'6', rowSeat: 'A',numberSeat: '6', selected: false},
      {id:'7', rowSeat: 'A',numberSeat: '7', selected: false},
      {id:'8', rowSeat: 'A',numberSeat: '8', selected: false},
      {id:'9', rowSeat: 'A',numberSeat: '9', selected: false},
      {id:'10', rowSeat: 'A',numberSeat: '10', selected: false},
      {id:'1', rowSeat: 'B',numberSeat: '1', selected: false},
      {id:'2', rowSeat: 'B',numberSeat: '2', selected: false},
      {id:'3', rowSeat: 'B',numberSeat: '3', selected: false},
      {id:'4', rowSeat: 'B',numberSeat: '4', selected: false},
      {id:'5', rowSeat: 'B',numberSeat: '5', selected: false},
      {id:'6', rowSeat: 'B',numberSeat: '6', selected: false},
      {id:'7', rowSeat: 'B',numberSeat: '7', selected: false},
      {id:'8', rowSeat: 'B',numberSeat: '8', selected: false},
      {id:'9', rowSeat: 'B',numberSeat: '9', selected: false},
      {id:'10', rowSeat: 'B',numberSeat: '10', selected: false},
      {id:'1', rowSeat: 'C',numberSeat: '1', selected: false},
      {id:'2', rowSeat: 'C',numberSeat: '2', selected: false},
      {id:'3', rowSeat: 'C',numberSeat: '3', selected: false},
      {id:'4', rowSeat: 'C',numberSeat: '4', selected: false},
      {id:'5', rowSeat: 'C',numberSeat: '5', selected: false},
      {id:'6', rowSeat: 'C',numberSeat: '6', selected: false},
      {id:'7', rowSeat: 'C',numberSeat: '7', selected: false},
      {id:'8', rowSeat: 'C',numberSeat: '8', selected: false},
      {id:'9', rowSeat: 'C',numberSeat: '9', selected: false},
      {id:'10', rowSeat: 'C',numberSeat: '10', selected: false},
      {id:'1', rowSeat: 'D',numberSeat: '1', selected: false},
      {id:'2', rowSeat: 'D',numberSeat: '2', selected: false},
      {id:'3', rowSeat: 'D',numberSeat: '3', selected: false},
      {id:'4', rowSeat: 'D',numberSeat: '4', selected: false},
      {id:'5', rowSeat: 'D',numberSeat: '5', selected: false},
      {id:'6', rowSeat: 'D',numberSeat: '6', selected: false},
      {id:'7', rowSeat: 'D',numberSeat: '7', selected: false},
      {id:'8', rowSeat: 'D',numberSeat: '8', selected: false},
      {id:'9', rowSeat: 'D',numberSeat: '9', selected: false},
      {id:'10', rowSeat: 'D',numberSeat: '10', selected: false},
      {id:'1', rowSeat: 'E',numberSeat: '1', selected: false},
      {id:'2', rowSeat: 'E',numberSeat: '2', selected: false},
      {id:'3', rowSeat: 'E',numberSeat: '3', selected: false},
      {id:'4', rowSeat: 'E',numberSeat: '4', selected: false},
      {id:'5', rowSeat: 'E',numberSeat: '5', selected: false},
      {id:'6', rowSeat: 'E',numberSeat: '6', selected: false},
      {id:'7', rowSeat: 'E',numberSeat: '7', selected: false},
      {id:'8', rowSeat: 'E',numberSeat: '8', selected: false},
      {id:'9', rowSeat: 'E',numberSeat: '9', selected: false},
      {id:'10', rowSeat: 'E',numberSeat: '10', selected: false},
      {id:'1', rowSeat: 'F',numberSeat: '1', selected: false},
      {id:'2', rowSeat: 'F',numberSeat: '2', selected: false},
      {id:'3', rowSeat: 'F',numberSeat: '3', selected: false},
      {id:'4', rowSeat: 'F',numberSeat: '4', selected: false},
      {id:'5', rowSeat: 'F',numberSeat: '5', selected: false},
      {id:'6', rowSeat: 'F',numberSeat: '6', selected: false},
      {id:'7', rowSeat: 'F',numberSeat: '7', selected: false},
      {id:'8', rowSeat: 'F',numberSeat: '8', selected: false},
      {id:'9', rowSeat: 'F',numberSeat: '9', selected: false},
      {id:'10', rowSeat: 'F',numberSeat: '10', selected: false},
      {id:'1', rowSeat: 'G',numberSeat: '1', selected: false},
      {id:'2', rowSeat: 'G',numberSeat: '2', selected: false},
      {id:'3', rowSeat: 'G',numberSeat: '3', selected: false},
      {id:'4', rowSeat: 'G',numberSeat: '4', selected: false},
      {id:'5', rowSeat: 'G',numberSeat: '5', selected: false},
      {id:'6', rowSeat: 'G',numberSeat: '6', selected: false},
      {id:'7', rowSeat: 'G',numberSeat: '7', selected: false},
      {id:'8', rowSeat: 'G',numberSeat: '8', selected: false},
      {id:'9', rowSeat: 'G',numberSeat: '9', selected: false},
      {id:'10', rowSeat: 'G',numberSeat: '10', selected: false},
      {id:'1', rowSeat: 'H',numberSeat: '1', selected: false},
      {id:'2', rowSeat: 'H',numberSeat: '2', selected: false},
      {id:'3', rowSeat: 'H',numberSeat: '3', selected: false},
      {id:'4', rowSeat: 'H',numberSeat: '4', selected: false},
      {id:'5', rowSeat: 'H',numberSeat: '5', selected: false},
      {id:'6', rowSeat: 'H',numberSeat: '6', selected: false},
      {id:'7', rowSeat: 'H',numberSeat: '7', selected: false},
      {id:'8', rowSeat: 'H',numberSeat: '8', selected: false},
      {id:'9', rowSeat: 'H',numberSeat: '9', selected: false},
      {id:'10', rowSeat: 'H',numberSeat: '10', selected: false},
    ]
  }
}

export default storeCOnfig;